name: Test App

on:
  push:
    branches:
      - feature_testing
  pull_request:
    branches:
      - feature_testing

jobs:
  unit_test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Unit tests
        run: ./gradlew testDebugUnitTest
      - name: Unit tests results
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-results
          path: app/build/reports/tests/testDebugUnitTest/index.html

  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Lint Check Run
        run: ./gradlew lintDebug
      - name: Lint Check Results
        uses: actions/upload-artifact@v4
        with:
          name: lint-check-results
          path: app/build/reports/lint-results-debug.html

  android_test:
    name: Instrumented Tests
    runs-on: macos-13
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Instrumented Tests Run
        uses: ReactiveCircus/android-emulator-runner@v2.32.0
        with:
          api-level: 29
          arch: x86_64
          script: ./gradlew connectedDebugAndroidTest
      - name: Instrumented Tests Results
        uses: actions/upload-artifact@v4
        with:
          name: instrumented-tests-results
          path: app/build/reports/androidTests/connected/debug/index.html